-- ============================================================
-- AI School - finance import from AI_School.xlsx (2026-10-10)
-- Creates: coded chart of accounts (5100-5790), staff departments + staff
-- (variable-pay freelancers: no fixed salary), every expense row of the
-- «المصروفات» sheet as an approved expense (payroll of months 5 and 6 split
-- per person, month-8 payroll attached as itemised lines) and the 5 operating
-- transfers from فارس بن عبد العزيز.
-- Total imported expenses = 86,276.32 SAR (= sheet total 86,105.32 + the
-- uncategorised «كارتات 171» row).
-- Safe to run once: it stops if the import already exists. To redo it:
--   DELETE FROM expenses WHERE source = 'import_xlsx';
--   DELETE FROM finance_funding WHERE source = 'import_xlsx';
-- TAKE A DB BACKUP FIRST.
-- ============================================================
BEGIN;
DO $$
DECLARE admin_id uuid;
BEGIN
  SELECT id INTO admin_id FROM users ORDER BY created_at ASC LIMIT 1;
  IF admin_id IS NULL THEN RAISE EXCEPTION 'No user found to attribute the import to'; END IF;
  IF EXISTS (SELECT 1 FROM expenses WHERE source = 'import_xlsx') THEN
    RAISE NOTICE 'Finance import already present - nothing done.'; RETURN;
  END IF;

  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'اشتراكات وخدمات', 'اشتراكات وخدمات', '5100', NULL, 5100, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5100');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'أدوات الذكاء الاصطناعي والتصميم', 'أدوات الذكاء الاصطناعي والتصميم', '5110', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), 5110, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5110');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'اجتماعات زوم', 'اجتماعات زوم', '5120', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), 5120, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5120');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'الاتصالات وشرائح الاتصال', 'الاتصالات وشرائح الاتصال', '5130', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), 5130, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5130');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'الرسائل والبريد والأدوات المكتبية', 'الرسائل والبريد والأدوات المكتبية', '5140', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), 5140, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5140');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق التصميم', 'فريق التصميم', '5200', NULL, 5200, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5200');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'تصميم ملفات العرض', 'تصميم ملفات العرض', '5210', (SELECT id FROM expense_categories WHERE code = '5200' ORDER BY created_at LIMIT 1), 5210, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5210');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'مصممو الجرافيك', 'مصممو الجرافيك', '5220', (SELECT id FROM expense_categories WHERE code = '5200' ORDER BY created_at LIMIT 1), 5220, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5220');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'أجور الفريق (بالإنجاز)', 'أجور الفريق (بالإنجاز)', '5300', NULL, 5300, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5300');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'المعلمون', 'المعلمون', '5310', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), 5310, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5310');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق المحتوى التعليمي', 'فريق المحتوى التعليمي', '5320', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), 5320, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5320');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'التسويق وشراء الإعلانات', 'التسويق وشراء الإعلانات', '5330', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), 5330, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5330');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'خدمة العملاء', 'خدمة العملاء', '5340', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), 5340, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5340');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'التصميم', 'التصميم', '5350', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), 5350, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5350');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق المحتوى والتسويق', 'فريق المحتوى والتسويق', '5400', NULL, 5400, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5400');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'تصوير الفيديوهات', 'تصوير الفيديوهات', '5410', (SELECT id FROM expense_categories WHERE code = '5400' ORDER BY created_at LIMIT 1), 5410, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5410');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'إدارة السوشيال ميديا', 'إدارة السوشيال ميديا', '5420', (SELECT id FROM expense_categories WHERE code = '5400' ORDER BY created_at LIMIT 1), 5420, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5420');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'تصميم المحتوى التعليمي', 'تصميم المحتوى التعليمي', '5500', NULL, 5500, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5500');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق إعداد المحتوى', 'فريق إعداد المحتوى', '5510', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), 5510, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5510');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق المتابعة', 'فريق المتابعة', '5520', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), 5520, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5520');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'ميزانية الحملات الإعلانية', 'ميزانية الحملات الإعلانية', '5600', NULL, 5600, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5600');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'الحملات الممولة', 'الحملات الممولة', '5610', (SELECT id FROM expense_categories WHERE code = '5600' ORDER BY created_at LIMIT 1), 5610, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5610');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'إنتاج مواد الحملات', 'إنتاج مواد الحملات', '5620', (SELECT id FROM expense_categories WHERE code = '5600' ORDER BY created_at LIMIT 1), 5620, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5620');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'مصاريف أخرى', 'مصاريف أخرى', '5700', NULL, 5700, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5700');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'رسوم التحويلات الدولية', 'رسوم التحويلات الدولية', '5710', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), 5710, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5710');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'اعتماد STEM', 'اعتماد STEM', '5720', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), 5720, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5720');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'مونتاج', 'مونتاج', '5730', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), 5730, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5730');
  INSERT INTO expense_categories (id, name, name_ar, code, parent_id, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'تحتاج مراجعة', 'تحتاج مراجعة', '5790', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), 5790, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM expense_categories WHERE code = '5790');
  INSERT INTO staff_departments (id, name, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'المدرّسون', 1, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_departments WHERE name = 'المدرّسون');
  INSERT INTO staff_departments (id, name, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق المحتوى التعليمي', 2, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_departments WHERE name = 'فريق المحتوى التعليمي');
  INSERT INTO staff_departments (id, name, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق المتابعة', 3, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_departments WHERE name = 'فريق المتابعة');
  INSERT INTO staff_departments (id, name, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق التسويق', 4, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_departments WHERE name = 'فريق التسويق');
  INSERT INTO staff_departments (id, name, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'فريق التصميم', 5, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_departments WHERE name = 'فريق التصميم');
  INSERT INTO staff_departments (id, name, display_order, is_archived, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'خدمة العملاء', 6, false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_departments WHERE name = 'خدمة العملاء');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'ميمونة', (SELECT id FROM staff_departments WHERE name = 'المدرّسون' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'ميمونة');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'اسراء', (SELECT id FROM staff_departments WHERE name = 'المدرّسون' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'اسراء');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'هدير', (SELECT id FROM staff_departments WHERE name = 'المدرّسون' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'هدير');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'الاء', (SELECT id FROM staff_departments WHERE name = 'المدرّسون' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'الاء');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'نورهان', (SELECT id FROM staff_departments WHERE name = 'المدرّسون' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'نورهان');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'احمد محمد', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'ahmed0work568@gmail.com', '+201026810170', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'احمد محمد');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'رحاب', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'naderrehab02@gmail.com', '+201008597599', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'رحاب');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'احلام', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'rshdy829@gmail.com', '+201065314528', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'احلام');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'مصطفى علي', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'mustafaali4813@gmail.com', '+201032029374', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'مصطفى علي');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'سالم', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'salemalielfaidey@gmail.com', '+201113103654', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'سالم');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'هبة', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'هبة');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'محمد خالد', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'mohamed33badea@gmail.com', '+201093980792', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'محمد خالد');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'روضة', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'rawdam819@gmail.com', '+201068395984', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'روضة');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'احمد ايمن', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'ahmadayman4377@gmail.com', '+201275491242', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'احمد ايمن');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'عبدالرحمن صلاح', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'abdelrahmanthegost2015@gmail.com', '+201281579550', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'عبدالرحمن صلاح');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'احمد عبدالناصر', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'ahmed.abdelnasser.363@gmail.com', '+201090438405', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'احمد عبدالناصر');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'شادي محمد', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'shadysamea111@gmail.com', '+201017798223', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'شادي محمد');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'احمد جودة', (SELECT id FROM staff_departments WHERE name = 'فريق المحتوى التعليمي' LIMIT 1), 'ahmedgoda712@gmail.com', '+201212265381', NULL, 'SAR', false, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'احمد جودة');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'حسين علي', (SELECT id FROM staff_departments WHERE name = 'فريق المتابعة' LIMIT 1), 'hussien3bdelmaksoud@gmail.com', '+201101313215', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'حسين علي');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'اية', (SELECT id FROM staff_departments WHERE name = 'فريق التسويق' LIMIT 1), NULL, '+201025597296', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'اية');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'مصطفى (ميديا باير)', (SELECT id FROM staff_departments WHERE name = 'فريق التسويق' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'مصطفى (ميديا باير)');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'احمد سيد', (SELECT id FROM staff_departments WHERE name = 'فريق التصميم' LIMIT 1), NULL, '+201017522669', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'احمد سيد');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'مازن', (SELECT id FROM staff_departments WHERE name = 'فريق التصميم' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'مازن');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'اميرة', (SELECT id FROM staff_departments WHERE name = 'فريق التصميم' LIMIT 1), NULL, '+201022849950', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'اميرة');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'باسم', (SELECT id FROM staff_departments WHERE name = 'فريق التصميم' LIMIT 1), NULL, '+201110639733', NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'باسم');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'ابرار', (SELECT id FROM staff_departments WHERE name = 'خدمة العملاء' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'ابرار');
  INSERT INTO staff_members (id, full_name, department_id, email, phone, base_salary, currency, is_active, created_by, created_at, updated_at)
  SELECT gen_random_uuid(), 'الزهراء', (SELECT id FROM staff_departments WHERE name = 'خدمة العملاء' LIMIT 1), NULL, NULL, NULL, 'SAR', true, admin_id, now(), now()
  WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE full_name = 'الزهراء');
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1320.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'روضة' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — روضة (شهر 6)', 'روضة', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (12 محاضرة)", "amount": "1200.00"}, {"label": "بونص 10%", "amount": "120.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 660.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'سالم' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — سالم (شهر 6)', 'سالم', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (6 محاضرة)", "amount": "600.00"}, {"label": "بونص 10%", "amount": "60.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1008.34, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد ايمن' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — احمد ايمن (شهر 6)', 'احمد ايمن', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (10 محاضرة)", "amount": "916.67"}, {"label": "بونص 10%", "amount": "91.67"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1159.58, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احلام' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — احلام (شهر 6)', 'احلام', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (11 محاضرة)", "amount": "1008.33"}, {"label": "بونص 15%", "amount": "151.25"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1000.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'مصطفى علي' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — مصطفى علي (شهر 6)', 'مصطفى علي', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (8 محاضرة)", "amount": "800.00"}, {"label": "بونص 25%", "amount": "200.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 875.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'روضة' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — روضة (شهر 6)', 'روضة', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (7 محاضرة)", "amount": "700.00"}, {"label": "بونص 25%", "amount": "175.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 920.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'محمد خالد' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — محمد خالد (شهر 6)', 'محمد خالد', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (8 محاضرة)", "amount": "766.67"}, {"label": "بونص 20%", "amount": "153.33"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 990.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد محمد' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — احمد محمد (شهر 6)', 'احمد محمد', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (9 محاضرة)", "amount": "825.00"}, {"label": "بونص 20%", "amount": "165.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 770.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'عبدالرحمن صلاح' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — عبدالرحمن صلاح (شهر 6)', 'عبدالرحمن صلاح', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (7 محاضرة)", "amount": "700.00"}, {"label": "بونص 10%", "amount": "70.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 460.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد عبدالناصر' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — احمد عبدالناصر (شهر 6)', 'احمد عبدالناصر', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (4 محاضرة)", "amount": "400.00"}, {"label": "بونص 15%", "amount": "60.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 750.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'رحاب' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — رحاب (شهر 6)', 'رحاب', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (6.25 محاضرة)", "amount": "625.00"}, {"label": "بونص 20%", "amount": "125.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1140.00, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5510' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'شادي محمد' ORDER BY created_at LIMIT 1), 'فريق إعداد المحتوى — شادي محمد (شهر 6)', 'شادي محمد', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (9.5 محاضرة)", "amount": "950.00"}, {"label": "بونص 20%", "amount": "190.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 517.50, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5520' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'حسين علي' ORDER BY created_at LIMIT 1), 'فريق المتابعة — حسين علي (شهر 6)', 'حسين علي', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (9 محاضرة)", "amount": "450.00"}, {"label": "بونص 15%", "amount": "67.50"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 622.50, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5520' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد ايمن' ORDER BY created_at LIMIT 1), 'فريق المتابعة — احمد ايمن (شهر 6)', 'احمد ايمن', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (9 محاضرة)", "amount": "375.00"}, {"label": "بونص 66%", "amount": "247.50"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 749.99, 'SAR', '2026-06-30', (SELECT id FROM expense_categories WHERE code = '5500' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5520' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد محمد' ORDER BY created_at LIMIT 1), 'فريق المتابعة — احمد محمد (شهر 6)', 'احمد محمد', NULL, NULL, 'التاريخ غير مسجّل في الملف الأصلي (تم وضع نهاية الشهر). المبلغ من كشف «رواتب شهر 6».', NULL, NULL, NULL, '2026-06', '[{"label": "أجر المحاضرات (9 محاضرة)", "amount": "375.00"}, {"label": "بونص 100%", "amount": "374.99"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 6000.00, 'SAR', '2026-06-10', (SELECT id FROM expense_categories WHERE code = '5600' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5610' ORDER BY created_at LIMIT 1), NULL, NULL, 'حملات اعلانية — حمالات اعلانية للتوعية لمدة شهر', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 250.00, 'SAR', '2026-06-10', (SELECT id FROM expense_categories WHERE code = '5600' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5620' ORDER BY created_at LIMIT 1), NULL, NULL, 'تصوير 4 فيديوهات مودل — رسوم مودل', NULL, NULL, NULL, 'تم دفع الباقي من طرف المثنى', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 77.00, 'SAR', '2026-06-11', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5110' ORDER BY created_at LIMIT 1), NULL, NULL, 'claude — لمساعدة انشاء المحتوى', 'Claude (Anthropic)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1000.00, 'SAR', '2026-06-18', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5730' ORDER BY created_at LIMIT 1), NULL, NULL, 'مونتاج', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1333.00, 'SAR', '2026-06-10', (SELECT id FROM expense_categories WHERE code = '5200' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5220' ORDER BY created_at LIMIT 1), NULL, NULL, 'تصاميم جرافك — رواتب ٣ موضفين فريلانسر جرافيك', NULL, NULL, NULL, 'المبلغ الأصلي 17,602 جنيه مصري (احمد 12,811 / باسم 2,500 / اميرة 2,291) — محوّل إلى الريال', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 186.07, 'SAR', '2026-07-02', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5110' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك freepik — اشتراك بخصوص التصاميم المستخدمة https://www.freepik.com/pricing', 'Freepik', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1017.25, 'SAR', '2026-07-04', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5330' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'مصطفى (ميديا باير)' ORDER BY created_at LIMIT 1), 'مصطفي ميدا باير — راتب ميديا باير', 'مصطفى (ميديا باير)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 9500.00, 'SAR', '2026-07-05', (SELECT id FROM expense_categories WHERE code = '5600' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5610' ORDER BY created_at LIMIT 1), NULL, NULL, 'حملات اعلانية شهر ٧ — حملات اعلانية', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 823.25, 'SAR', '2026-07-05', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد محمد' ORDER BY created_at LIMIT 1), 'احمد محمد تيم ليدر — راتب عضو فرق المحتوى التعليمي', 'احمد محمد', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 713.25, 'SAR', '2026-07-05', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'رحاب' ORDER BY created_at LIMIT 1), 'رحاب (محتوى تعليمي) — راتب عضو فريق المحتوى العليمي', 'رحاب', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 713.25, 'SAR', '2026-07-05', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احلام' ORDER BY created_at LIMIT 1), 'احلام (محتوى تعليمي) — راتب فريق المحتوى التعليمي', 'احلام', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 530.25, 'SAR', '2026-07-05', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5330' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'اية' ORDER BY created_at LIMIT 1), 'اية — راتب كتابه المحتوى', 'اية', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 343.25, 'SAR', '2026-07-05', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5350' ORDER BY created_at LIMIT 1), NULL, NULL, 'احمد جرافيك — راتب مصمم الجرافيك', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 171.00, 'SAR', '2026-07-06', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5140' ORDER BY created_at LIMIT 1), NULL, NULL, 'لارسال الرسايل — اشتراك كارتات', 'كارتات', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 77.00, 'SAR', '2026-07-11', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5110' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك كلاود — لمساعدة انشاء المحتوى', 'Claude (Anthropic)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 37.19, 'SAR', '2026-07-22', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5140' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك مايكروسوفت — ااشتراك مايكروسوفت', 'Microsoft', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 244.32, 'SAR', '2026-07-26', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5120' ORDER BY created_at LIMIT 1), NULL, NULL, 'زوم ميتينج — زوم ميتنق ٤ اشتراكات', 'Zoom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 7820.00, 'SAR', '2026-07-01', (SELECT id FROM expense_categories WHERE code = '5600' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5610' ORDER BY created_at LIMIT 1), NULL, NULL, 'حملات اعلانية شهر 8 — حملات اعلانية', NULL, NULL, NULL, 'التصنيف الأصلي في الملف: رواتب الموظفين', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1017.00, 'SAR', '2026-08-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5330' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'مصطفى (ميديا باير)' ORDER BY created_at LIMIT 1), 'راتب مصطفى ميديا باير', 'مصطفى (ميديا باير)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1347.00, 'SAR', '2026-08-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد محمد' ORDER BY created_at LIMIT 1), 'راتب احمد محمد تيم ليدر', 'احمد محمد', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1247.00, 'SAR', '2026-08-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احلام' ORDER BY created_at LIMIT 1), 'راتب احلام فريق المحتوى', 'احلام', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1197.00, 'SAR', '2026-08-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'رحاب' ORDER BY created_at LIMIT 1), 'راتب رحاب فريق المحتوى', 'رحاب', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 717.00, 'SAR', '2026-08-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5330' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'اية' ORDER BY created_at LIMIT 1), 'راتب اية', 'اية', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 767.00, 'SAR', '2026-08-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), NULL, NULL, NULL, 'راتب احمد', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 137.00, 'SAR', '2026-08-03', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'رحاب' ORDER BY created_at LIMIT 1), 'راتب رحاب فريق المحتوى', 'رحاب', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1266.41, 'SAR', '2026-08-03', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5720' ORDER BY created_at LIMIT 1), NULL, NULL, 'اعتماد stem — اعتماد اكاديمية', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 379.00, 'SAR', '2026-08-02', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5130' ORDER BY created_at LIMIT 1), NULL, NULL, 'شريحتين لتكليم العملاء — شريحتين اتصال', 'شرائح اتصال', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 81.30, 'SAR', '2026-08-03', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5140' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك ايميلات هوستنجر — ايميلات', 'Hostinger', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 61.80, 'SAR', '2026-08-05', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5120' ORDER BY created_at LIMIT 1), NULL, NULL, 'زوم ميتينج — اشتراك', 'Zoom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 171.00, 'SAR', '2026-08-09', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5140' ORDER BY created_at LIMIT 1), NULL, NULL, 'كارتات', 'كارتات', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 77.00, 'SAR', '2026-08-11', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5110' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك كلاود — لمساعدة انشاء المحتوى', 'Claude (Anthropic)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 32.34, 'SAR', '2026-08-23', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5140' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك مايكروسوفت — ااشتراك مايكروسوفت', 'Microsoft', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1040.00, 'SAR', '2026-09-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5310' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'هدير' ORDER BY created_at LIMIT 1), 'راتب هدير معلمة', 'هدير', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "60 مجانية", "amount": "900.00"}, {"label": "7 مشترك", "amount": "105.00"}, {"label": "بونص اشتراك", "amount": "20.00"}, {"label": "ساعة اضافية", "amount": "15.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 652.25, 'SAR', '2026-09-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5310' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'نورهان' ORDER BY created_at LIMIT 1), 'راتب نوهان معلمة', 'نورهان', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "36 سيشن مجاني", "amount": "540.00"}, {"label": "5 محاضره اشتراك", "amount": "75.00"}, {"label": "بونص اشتراك", "amount": "20.00"}, {"label": "فرق عن كشف الراتب (رسوم تحويل/تسوية)", "amount": "17.25"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 757.25, 'SAR', '2026-09-02', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5310' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'الاء' ORDER BY created_at LIMIT 1), 'راتب الاء معلمة', 'الاء', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "46 محاضره مجانيه", "amount": "690.00"}, {"label": "2 محاضره اشتراك", "amount": "30.00"}, {"label": "بونص اشتراك", "amount": "20.00"}, {"label": "فرق عن كشف الراتب (رسوم تحويل/تسوية)", "amount": "17.25"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1792.25, 'SAR', '2026-09-10', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5310' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'ميمونة' ORDER BY created_at LIMIT 1), 'راتب ميمونة معلمة', 'ميمونة', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "45 مجانية", "amount": "675.00"}, {"label": "11 فديو", "amount": "1100.00"}, {"label": "فرق عن كشف الراتب (رسوم تحويل/تسوية)", "amount": "17.25"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1230.00, 'SAR', '2026-09-10', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5310' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'اسراء' ORDER BY created_at LIMIT 1), 'راتب اسراء معلمة', 'اسراء', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "60 مجانية", "amount": "900.00"}, {"label": "10 محاضره اشتراك", "amount": "150.00"}, {"label": "stem", "amount": "100.00"}, {"label": "4 بونص اشتراك", "amount": "80.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1350.58, 'SAR', '2026-09-10', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5340' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'الزهراء' ORDER BY created_at LIMIT 1), 'راتب الزهراء خدمة عملاء', 'الزهراء', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1250.00"}, {"label": "بونص", "amount": "150.00"}, {"label": "فرق عن كشف الراتب (رسوم تحويل/تسوية)", "amount": "-49.42"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1200.58, 'SAR', '2026-09-10', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5340' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'ابرار' ORDER BY created_at LIMIT 1), 'راتب ابرار خدمة عملاء', 'ابرار', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1250.00"}, {"label": "فرق عن كشف الراتب (رسوم تحويل/تسوية)", "amount": "-49.42"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1285.00, 'SAR', '2026-09-10', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'سالم' ORDER BY created_at LIMIT 1), 'راتب سالم فريق المحتوى', 'سالم', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1000.00"}, {"label": "راتب شهر 7", "amount": "285.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1270.00, 'SAR', '2026-09-10', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'هبة' ORDER BY created_at LIMIT 1), 'راتب هبة فريق المحتوى', 'هبة', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1000.00"}, {"label": "راتب شهر 7", "amount": "100.00"}, {"label": "بونص", "amount": "50.00"}, {"label": "Stem", "amount": "60.00"}, {"label": "تسجيل فديو", "amount": "60.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1160.00, 'SAR', '2026-09-10', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'رحاب' ORDER BY created_at LIMIT 1), 'راتب رحاب فريق المحتوى', 'رحاب', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1050.00"}, {"label": "بونص", "amount": "50.00"}, {"label": "stem", "amount": "60.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1560.00, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد محمد' ORDER BY created_at LIMIT 1), 'احمد محمد فريق المحتوى', 'احمد محمد', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1150.00"}, {"label": "stem", "amount": "100.00"}, {"label": "بونص", "amount": "100.00"}, {"label": "7 فديو", "amount": "210.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 975.00, 'SAR', '2026-09-13', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'مصطفى علي' ORDER BY created_at LIMIT 1), 'مصطفى علي فريق المحتوى', 'مصطفى علي', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 7", "amount": "225.00"}, {"label": "راتب شهر 8", "amount": "750.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 950.00, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'محمد خالد' ORDER BY created_at LIMIT 1), 'محمد خالد فريق المحتوى', 'محمد خالد', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "950.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 700.00, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5330' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'اية' ORDER BY created_at LIMIT 1), 'Aya تسويق', 'اية', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "700.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 700.00, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5350' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'مازن' ORDER BY created_at LIMIT 1), 'مازن تصميم', 'مازن', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "700.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 700.00, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5350' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احمد سيد' ORDER BY created_at LIMIT 1), 'احمد سيد تصميم', 'احمد سيد', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "700.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1000.00, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5330' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'مصطفى (ميديا باير)' ORDER BY created_at LIMIT 1), 'مصطفى ميديا باير', 'مصطفى (ميديا باير)', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1000.00"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1417.50, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5300' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5320' ORDER BY created_at LIMIT 1), NULL, (SELECT id FROM staff_members WHERE full_name = 'احلام' ORDER BY created_at LIMIT 1), 'احلام', 'احلام', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08', '[{"label": "راتب شهر 8", "amount": "1050.00"}, {"label": "7 فديو", "amount": "420.00"}, {"label": "تأخير 1", "amount": "-21.00"}, {"label": "تأخير 2", "amount": "-31.50"}]'::jsonb, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 172.05, 'SAR', '2026-09-11', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5710' ORDER BY created_at LIMIT 1), NULL, NULL, 'رسوم تحويل دولي — رسوم تحويل الدولي للموضفين', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 34.50, 'SAR', '2026-09-14', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5130' ORDER BY created_at LIMIT 1), NULL, NULL, 'رسوم اصدار شريحة — شريحة stc للحملات الاعلانيه', 'STC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 159.52, 'SAR', '2026-09-14', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5120' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك زوم — ٥ اشتراكات زوم', 'Zoom', NULL, NULL, 'التصنيف الأصلي في الملف: مصاريف اخرى', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 77.60, 'SAR', '2026-09-19', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5110' ORDER BY created_at LIMIT 1), NULL, NULL, 'اشتراك كلود', 'Claude (Anthropic)', NULL, NULL, 'التصنيف الأصلي في الملف: مصاريف اخرى', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 172.50, 'SAR', '2026-09-22', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5130' ORDER BY created_at LIMIT 1), NULL, NULL, 'شريحتين stc', 'STC', NULL, NULL, 'التصنيف الأصلي في الملف: مصاريف اخرى', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 102.53, 'SAR', '2026-09-26', (SELECT id FROM expense_categories WHERE code = '5600' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5610' ORDER BY created_at LIMIT 1), NULL, NULL, 'حمله — تست حمله اعلانيه شات جبتي', NULL, NULL, NULL, 'التصنيف الأصلي في الملف: مصاريف اخرى', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 1214.67, 'SAR', '2026-09-26', (SELECT id FROM expense_categories WHERE code = '5700' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5720' ORDER BY created_at LIMIT 1), NULL, NULL, 'اعتماد ستيم — استكمال مبلغ اعتماد ستيم', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expenses (id, amount, currency, expense_date, category_id, subcategory_id, budget_line_id, staff_id, description, vendor, invoice_number, payment_method, notes, invoice_date, invoice_url, paid_by, period_month, breakdown, source, status, current_version, created_by, approved_by, approved_at, is_archived, created_at, updated_at) VALUES (gen_random_uuid(), 171.00, 'SAR', '2026-09-28', (SELECT id FROM expense_categories WHERE code = '5100' ORDER BY created_at LIMIT 1), (SELECT id FROM expense_categories WHERE code = '5140' ORDER BY created_at LIMIT 1), NULL, NULL, 'كارتات — اشتراك كارتات', 'كارتات', NULL, NULL, 'التصنيف الأصلي في الملف: بدون تصنيف', NULL, NULL, NULL, NULL, NULL, 'import_xlsx', 'approved', 1, admin_id, admin_id, now(), false, now(), now());
  INSERT INTO expense_versions (id, expense_id, version_number, snapshot, change_reason, restored_from_version, created_by, created_at)
  SELECT gen_random_uuid(), e.id, 1, jsonb_build_object(
      'amount', e.amount::text, 'currency', e.currency, 'expense_date', to_char(e.expense_date, 'YYYY-MM-DD'),
      'category_id', e.category_id::text, 'subcategory_id', e.subcategory_id::text, 'budget_line_id', NULL,
      'staff_id', e.staff_id::text, 'description', e.description, 'vendor', e.vendor, 'invoice_number', e.invoice_number,
      'payment_method', e.payment_method, 'notes', e.notes, 'invoice_date', NULL, 'invoice_url', e.invoice_url,
      'paid_by', e.paid_by, 'period_month', e.period_month, 'breakdown', e.breakdown, 'status', e.status),
    'استيراد من ملف AI_School.xlsx', NULL, admin_id, now()
  FROM expenses e WHERE e.source = 'import_xlsx';
  INSERT INTO finance_funding (id, funding_date, amount, currency, source_name, note, source, created_by, created_at, updated_at)
  VALUES (gen_random_uuid(), '2026-05-15', 12942.00, 'SAR', 'فارس بن عبد العزيز', 'تحويلات فترة التشغيل', 'import_xlsx', admin_id, now(), now());
  INSERT INTO finance_funding (id, funding_date, amount, currency, source_name, note, source, created_by, created_at, updated_at)
  VALUES (gen_random_uuid(), '2026-05-31', 10000.00, 'SAR', 'فارس بن عبد العزيز', 'تحويلات فترة التشغيل', 'import_xlsx', admin_id, now(), now());
  INSERT INTO finance_funding (id, funding_date, amount, currency, source_name, note, source, created_by, created_at, updated_at)
  VALUES (gen_random_uuid(), '2026-07-03', 15000.00, 'SAR', 'فارس بن عبد العزيز', 'تحويلات فترة التشغيل', 'import_xlsx', admin_id, now(), now());
  INSERT INTO finance_funding (id, funding_date, amount, currency, source_name, note, source, created_by, created_at, updated_at)
  VALUES (gen_random_uuid(), '2026-08-01', 15000.00, 'SAR', 'فارس بن عبد العزيز', 'تحويلات فترة التشغيل', 'import_xlsx', admin_id, now(), now());
  INSERT INTO finance_funding (id, funding_date, amount, currency, source_name, note, source, created_by, created_at, updated_at)
  VALUES (gen_random_uuid(), '2026-09-09', 20000.00, 'SAR', 'فارس بن عبد العزيز', 'تحويلات فترة التشغيل', 'import_xlsx', admin_id, now(), now());
  INSERT INTO finance_funding (id, funding_date, amount, currency, source_name, note, source, created_by, created_at, updated_at)
  VALUES (gen_random_uuid(), '2026-09-22', 4640.00, 'SAR', 'فارس بن عبد العزيز', 'جزء من الإيرادات (اشتراكات الطلاب)', 'import_xlsx', admin_id, now(), now());
END $$;

-- ---------------- checks (should read: total 74121.62, funding 77582.00) ----------------
SELECT c.code, c.name, count(*) AS rows, sum(e.amount) AS total
FROM expenses e JOIN expense_categories c ON c.id = e.category_id
WHERE e.source = 'import_xlsx' GROUP BY c.code, c.name ORDER BY c.code;
SELECT (SELECT sum(amount) FROM expenses WHERE source = 'import_xlsx') AS imported_total,
       74121.62 AS expected_total,
       (SELECT sum(amount) FROM finance_funding WHERE source = 'import_xlsx') AS funding_total,
       (SELECT count(*) FROM expenses WHERE source = 'import_xlsx') AS expense_rows,
       (SELECT count(*) FROM expense_versions v JOIN expenses e ON e.id = v.expense_id WHERE e.source = 'import_xlsx') AS versions,
       (SELECT count(*) FROM expenses WHERE source = 'import_xlsx' AND breakdown IS NOT NULL) AS itemised_rows;
-- categories you created earlier by hand (no account code) - review / archive from the app
SELECT name FROM expense_categories WHERE code IS NULL AND is_archived = false ORDER BY name;
COMMIT;
